In [1]:
import numpy as np
hlo = np.arange(2 ,51, 3)
hlo

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [2]:
import numpy as np

list1 = []
list2 = []

for i in range(5):
    accept = int(input())
    list1.append(accept)

print("List1 :",list1)

for i in range(5):
    accept = int(input())
    list2.append(accept)

print("List2", list2)

# conversion of List to Array

array1 = np.array(list1)
array2 = np.array(list2)
print("List1 to array convert  :", array1)
print("List2 to array convert  :", array2)

# concatenation of arrays

array_concatination = np.concatenate((array1, array2))

print("concatenation of arrays are :", array_concatination)

# Sorting of array

print("Sorted array :", np.sort(array_concatination))

8
4
2
6
0
List1 : [8, 4, 2, 6, 0]
3
9
7
1
5
List2 [3, 9, 7, 1, 5]
List1 to array convert  : [8 4 2 6 0]
List2 to array convert  : [3 9 7 1 5]
concatenation of arrays are : [8 4 2 6 0 3 9 7 1 5]
Sorted array : [0 1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np

my_array = np.array([[11, 14, 27], [5, 8, 9], [1, 9, 17], [13, 7, 19]])
print("Dimensions of a nd array is :", my_array.ndim)

print("Size of an array is :", my_array.size)

Dimensions of a nd array is : 2
Size of an array is : 12


In [4]:
import numpy as np

arr = np.arange(int(input()))
print("1D array (shape) :", arr.shape)

array_row = arr[np.newaxis]
print("2D array for row is :", array_row.shape)

array_col = arr[:, np.newaxis]
print("2D array for column is :", array_col.shape)

5
1D array (shape) : (5,)
2D array for row is : (1, 5)
2D array for column is : (5, 1)


In [5]:
x = np.array([1, 2])
y = np.expand_dims(x, axis=0)
y


array([[1, 2]])

In [6]:
y.shape

(1, 2)

In [7]:
yz = np.expand_dims(x, axis=1)
yz

array([[1],
       [2]])

In [8]:
yz.shape

(2, 1)

In [9]:
import numpy as np

array1 = np.square([51, 14, 5, 8, 9, 26, 23, 5, 7])  # square of numpy array
array2 = np.square([14, 75, 8, 56, 9, 37, 4, 25, 6])  # square of numpy array


print(" horizontal stack:\n", np.hstack((array1, array2)))

print("vertical stack :\n ", np.vstack((array1, array2)))

 horizontal stack:
 [2601  196   25   64   81  676  529   25   49  196 5625   64 3136   81
 1369   16  625   36]
vertical stack :
  [[2601  196   25   64   81  676  529   25   49]
 [ 196 5625   64 3136   81 1369   16  625   36]]


In [10]:
import numpy as np
a = np.array( [10,10,50, 40, 4, 4, 4, 8, 7, 8, 9, 5, 6, 5, 4, 4, 12, 13, 13] )
print(a)
unique, counts = np.unique(a, return_counts=True)
print("Frequency of unique values:")
print(np.asarray((unique, counts)))

[10 10 50 40  4  4  4  8  7  8  9  5  6  5  4  4 12 13 13]
Frequency of unique values:
[[ 4  5  6  7  8  9 10 12 13 40 50]
 [ 5  2  1  1  2  1  2  1  2  1  1]]


In [11]:
import numpy as np

arr = np.array([4, 4, 4, 4, 8, 7, 8, 9, 5, 6, 5, 4, 4, 12, 13, 13])
print(arr)
unique, counts = np.unique(arr, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[ 4  4  4  4  8  7  8  9  5  6  5  4  4 12 13 13]
[[ 4  6]
 [ 5  2]
 [ 6  1]
 [ 7  1]
 [ 8  2]
 [ 9  1]
 [12  1]
 [13  2]]
